module(
    name = "nogo-analyzer",
)

bazel_dep(name = "gazelle", version = "0.44.0")
bazel_dep(name = "rules_go", version = "0.55.1")
# bazel_dep(name = "buildifier_prebuilt", version = "7.1.2")
# bazel_dep(name = "com_google_protobuf", version = "4.25.0")
# bazel_dep(name = "bazel_features", version = "1.12.0")
# bazel_dep(name = "rules_proto", version = "6.0.0")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.23.6")

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
# go_deps.gazelle_default_attributes(
#     directives = [
#         "gazelle:go_rule rules_go",
#     ],
# )

go_deps.from_file(
    go_work = "//:go.work",
)
use_repo(
    go_deps,
    "co_honnef_go_tools",
    "com_github_bazelbuild_buildtools",
    "com_github_golangci_gofmt",
    "com_github_golangci_golangci_lint",
    "com_github_golangci_prealloc",
    "com_github_gordonklaus_ineffassign",
    "com_github_kisielk_errcheck",
    "org_golang_x_tools",
)

go_deps.module_override(
    path = "github.com/golangci/golangci-lint",
    patches = [
        # "//golangci-lint/patch:001_export_source.patch",
        "//golangci-lint/patch:002_export_getter.patch",
    ],
    patch_strip = 1,
    # patch_args = ["-p1"],
)

#     go_repository(
#         name = "com_github_golangci_golangci_lint",
#         importpath = "github.com/golangci/golangci-lint",
#         patch_args = ["-p1"],  #keep
#         patches = [
#             "@com_github_sluongng_nogo_analyzer//golangci-lint/patch:001_export_source.patch",
#             "@com_github_sluongng_nogo_analyzer//golangci-lint/patch:002_export_getter.patch",
#         ],  #keep
#         sum = "h1:CRRLu1JbhK5avLABFJ/OHVSQ0Ie5c4ulsOId1h3TTks=",
#         version = "v1.59.1",
#     )
